name: "bearer-pr-test"
description: ""
inputs:
  GIT_TOKEN:
    description: "GitHub Token from the repository"
    required: true
  gh_pages_url:
    description: "gh_page_ url"
    required: false
    default: https://tetrisiq.github.io/bearer-pr-test/
  ph_page_repo:
    description: "ph_page_repo"
    required: false
    default: https://github.com/TetrisIQ/bearer-pr-test

runs:
  using: "composite"
  steps:
    - uses: "actions/checkout@v4"
    - id: check
      uses: bearer/bearer-action@v2
      with:
        format: json
        output: securityTest.json
        exit-code: 0
    - id: findings
      shell: bash
      run: echo security_finding=$(cat securityTest.json | jq '. != {}')  >> $GITHUB_OUTPUT

    - id: gen_html
      if: steps.findings.outputs.security_finding == 'true'
      name: Generate HTML
      uses: bearer/bearer-action@v2
      with:
        format: html
        output: securityTest.html
        exit-code: 0
    - uses: actions/github-script@v6
      id: "comment_to_pr"
      if: steps.findings.outputs.security_finding == 'true'
      name: "Comment to PR"
      with:
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          })
          const botComment = comments.find(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('https://avatars.githubusercontent.com/u/36886676?s=48&v=4')
          })

          const commentBody = "# \![](https://avatars.githubusercontent.com/u/36886676?s=48&v=4) Bearer Report\nWe found some issues in your `code`:\nTake a look at the report here: ${{ inputs.gh_pages_url }}pr/${{ github.event.number }}/security/securityTest.html";

          if (botComment) {
            github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: commentBody
            })
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
          }

    - id: upload_artifact
      if: steps.findings.outputs.security_finding == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: securityHTML
        path: securityTest.html

    - id: open_groupe
      run: echo ${{ inputs.gh_page_repo }}
      shell: bash

    - id: checkout
      if: steps.findings.outputs.security_finding == 'true'
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        repository: "${{ inputs.gh_page_repo }}"
        token: ${{ inputs.GIT_TOKEN }}

    - id: download_artifact
      if: steps.findings.outputs.security_finding == 'true'
      uses: actions/download-artifact@v3
      with:
        name: securityHTML
        path: ${{ github.repository }}/pr/${{ github.event.number }}/security

    - id: upload_html_to_page
      if: steps.findings.outputs.security_finding == 'true'
      name: "Upload to GH Page branch"
      shell: bash
      run: |
        git config --global user.name 'TetrisIQ'
        git config --global user.email '24246993+TetrisIQ@users.noreply.github.com'
        git add . 
        git commit -am "Automated report"
        git push
        echo "::endgroup::"
